# Generated by Django 3.0.3 on 2020-03-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_order_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivary', 'Out for delivary'), ('Delivered', 'Delivered')], max_length=100),
        ),
    ]
